package uk.co.jonathonhenderson.adventofcode.days

import org.junit.jupiter.api.Test

class Day07Test extends DayTest {
    @Override
    def input() {
        """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """
    }

    @Test
    void part1() {
        expectPart1("21")
    }

    @Test
    void part2() {
        expectPart2("40")
    }
}